smtpHost: string
smtpPort: int
smtpUsername: string
smtpPassword: string
defaultFrom: string
allowedOrigin: string

redis:
  host: localhost
  port: 6379
  password: string
  topic: string
  enabled: false
  
kafka:
  enabled: true
  topic: string
  brokers:
    - kafka1:19092
  