defaultFrom: string
allowedOrigin: string

redis:
  host: localhost
  port: 6379
  password: string
  topic: string
  enabled: false

kafka:
  enabled: true
  topic: string
  brokers:
    - kafka1:19092

smtp:
  host: string
  port: int
  username: string
  password: string
